### ISSUE TITLE
온라인부스 폐쇄 및 리버브릿지 관리자 폐쇄

### ISSUE THREAD

**Issue by knh-8701** [predict-interactive/liverbridge-close#11]
온라인부스 3종 폐쇄 및 관리자페이지 폐쇄작업 필요합니다.
**아래 업무들에 대한 견적작성 필요**

1. 콘텐츠 백업,전달
2. 부스서버 클로징
3. 관리자 서버 클로징
----
*온라인부스 통계 관련 소스백업 필요없음
관리자페이지 : https://admin.liverbridge.co.kr -> 처리완료
베믈리디 1차 : https://vemlidy2.liverbridge.co.kr -> 처리완료
하보니 1차 : https://harvoni2.liverbridge.co.kr -> 처리완료
하보니 2차 : https://hcv.liverbridge.co.kr -> 처리완료

**Comment by sh-nam** [comment]
콘텐츠 백업: 지용
폐쇄: 오대표님
